version: '3.1'
services:
  ingresoapp-backend:
    image: ingresoapp-backend
    container_name: ingresoapp-backend
    restart: always
    build: 
      context: ./
    ports:  
    - "8291:8291"
    depends_on:
      -  ingresoapp-db
    networks:
    - network_cidenet

  ingresoapp-db:
    image: mysql:8.0
    container_name: ingresoapp-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cidenet
    networks:
    - network_cidenet
    
networks:
  network_cidenet:
     external: true
