spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost/cidenet_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username : root
    password: Hiko2589
server:  port: 8282